// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ywtzpsycgasomyvznwpp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl3dHpwc3ljZ2Fzb215dnpud3BwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NzExNTMsImV4cCI6MjA2MzQ0NzE1M30.-xBPsgl2kC_z526UXkKQetyqckbO5_WPctS5PGyuQRs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);